import * as db from '../config/db.js';
import {
  loadDueProcessPolicy,
  getScheduleFromPolicy,
  renderTemplate,
  formatViolationDates,
} from '../utils/dueProcessPolicy.js';
import {
  createCaseFromViolations,
  createCaseNotice,
  findOpenCaseForEmployee,
  attachViolationsToCase,
} from './disciplinaryCaseService.js';
import { logDueProcessAudit } from './dueProcessAuditService.js';
import { notifyHrPortalUsers } from './notificationService.js';

const extractTimePart = (value) => {
  if (!value) return null;
  if (typeof value === 'string') {
    if (value.includes(' ')) return value.split(' ')[1].slice(0, 5);
    if (value.includes('T')) return value.split('T')[1].slice(0, 5);
    return value.slice(0, 5);
  }
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${hours}:${minutes}`;
};

const timeToMinutes = (time) => {
  if (!time || typeof time !== 'string') return null;
  const [hh, mm] = time.split(':');
  const hours = Number(hh);
  const minutes = Number(mm);
  if (!Number.isFinite(hours) || !Number.isFinite(minutes)) return null;
  return hours * 60 + minutes;
};

const getAttendanceDurationMinutes = (timeIn, timeOut) => {
  const inMinutes = timeToMinutes(timeIn);
  const outMinutes = timeToMinutes(timeOut);
  if (inMinutes == null || outMinutes == null) return null;
  const duration = outMinutes - inMinutes;
  return duration >= 0 ? duration : null;
};

const buildPolicyRuleLabel = (violationType, rule) => {
  if (!rule) return null;
  const threshold = Number(rule.threshold || 0);
  const period = Number(rule.period_days || 0);
  return `${violationType}:${threshold}/${period}`;
};

export const createViolationRecord = async ({
  employeeId,
  attendanceId = null,
  violationType,
  violationMinutes = null,
  violationDate,
  policyRuleTriggered = null,
  autoGenerated = true,
  remarks = null,
  createdBy = null,
}) => {
  if (!employeeId || !violationType || !violationDate) return null;

  const existing = await db.getOne(
    `SELECT id FROM attendance_violations
     WHERE employee_id = ?
       AND attendance_id ${attendanceId ? '= ?' : 'IS NULL'}
       AND violation_type = ?
     LIMIT 1`,
    attendanceId ? [employeeId, attendanceId, violationType] : [employeeId, violationType]
  );

  if (existing?.id) {
    return existing.id;
  }

  const id = await db.insert('attendance_violations', {
    employee_id: employeeId,
    attendance_id: attendanceId,
    violation_type: violationType,
    violation_minutes: violationMinutes,
    violation_date: violationDate,
    policy_rule_triggered: policyRuleTriggered,
    auto_generated: autoGenerated ? 1 : 0,
    remarks,
  });

  await logDueProcessAudit({
    userId: createdBy,
    entityType: 'attendance_violation',
    entityId: id,
    action: 'create_violation',
    newValues: { violation_type: violationType, violation_date: violationDate },
  });

  return id;
};

export const evaluateAttendanceForViolations = async ({ attendance, createdBy = null }) => {
  if (!attendance) return [];

  const policy = await loadDueProcessPolicy();
  const schedule = getScheduleFromPolicy(policy) || {};

  const startTime = schedule.start_time || '08:00';
  const graceMinutes = Number(schedule.grace_period_minutes || 0);
  const requiredMinutes = Number(schedule.required_minutes || 480);

  const timeIn = extractTimePart(attendance.time_in);
  const timeOut = extractTimePart(attendance.time_out);
  const startMinutes = timeToMinutes(startTime);
  const timeInMinutes = timeToMinutes(timeIn);
  const timeOutMinutes = timeToMinutes(timeOut);
  const durationMinutes = getAttendanceDurationMinutes(timeIn, timeOut);

  const violations = [];

  if (attendance.status === 'absent') {
    violations.push({
      type: 'absence',
      minutes: null,
    });
  }

  if (attendance.status === 'late' && timeInMinutes != null && startMinutes != null) {
    const lateMinutes = Math.max(0, timeInMinutes - (startMinutes + graceMinutes));
    violations.push({
      type: 'late',
      minutes: lateMinutes,
    });
  }

  if (attendance.status === 'early_leave' && durationMinutes != null) {
    const undertimeMinutes = Math.max(0, requiredMinutes - durationMinutes);
    violations.push({
      type: 'undertime',
      minutes: undertimeMinutes,
    });
  }

  if ((attendance.status === 'present' || attendance.status === 'overtime') && durationMinutes != null) {
    const undertimeMinutes = Math.max(0, requiredMinutes - durationMinutes);
    if (undertimeMinutes > 0) {
      violations.push({
        type: 'undertime',
        minutes: undertimeMinutes,
      });
    }
  }

  if (attendance.status === 'overtime' && attendance.overtime_hours > 0) {
    const allowOtIfLate = policy?.overtime_rules?.allow_overtime_if_late !== false;
    const arrivedLate = startMinutes != null && timeInMinutes != null
      ? timeInMinutes > startMinutes + graceMinutes
      : false;

    if (!allowOtIfLate && arrivedLate) {
      violations.push({
        type: 'unauthorized_ot',
        minutes: Math.round(Number(attendance.overtime_hours || 0) * 60),
      });
    }
  }

  const today = new Date().toISOString().slice(0, 10);
  const isPastDate = attendance.date && attendance.date < today;
  if (attendance.status !== 'absent' && isPastDate && (!timeIn || !timeOut)) {
    violations.push({
      type: 'missing_log',
      minutes: null,
    });
  }

  const createdIds = [];
  for (const violation of violations) {
    const rule = policy?.violation_rules?.[violation.type] || null;
    const ruleLabel = buildPolicyRuleLabel(violation.type, rule);

    const violationId = await createViolationRecord({
      employeeId: attendance.employee_id,
      attendanceId: attendance.attendance_id || null,
      violationType: violation.type,
      violationMinutes: violation.minutes,
      violationDate: attendance.date,
      policyRuleTriggered: ruleLabel,
      autoGenerated: true,
      createdBy,
    });

    if (violationId) {
      createdIds.push({ id: violationId, type: violation.type });
    }
  }

  if (createdIds.length > 0) {
    await evaluateViolationThresholds({
      employeeId: attendance.employee_id,
      createdBy,
    });
  }

  return createdIds;
};

export const evaluateViolationThresholds = async ({ employeeId, createdBy = null }) => {
  const policy = await loadDueProcessPolicy();
  const rules = policy?.violation_rules || {};

  const triggeredCases = [];

  for (const [violationType, rule] of Object.entries(rules)) {
    const threshold = Number(rule?.threshold || 0);
    const periodDays = Number(rule?.period_days || 0);
    if (threshold <= 0 || periodDays <= 0) continue;

    const since = new Date();
    since.setDate(since.getDate() - periodDays);

    const countRow = await db.getOne(
      `SELECT COUNT(*) AS total
       FROM attendance_violations
       WHERE employee_id = ?
         AND violation_type = ?
         AND violation_date >= ?
         AND status <> 'dismissed'`,
      [employeeId, violationType, since.toISOString().slice(0, 10)]
    );

    const total = Number(countRow?.total || 0);
    if (total < threshold) continue;

    const violations = await db.getAll(
      `SELECT id, violation_date
       FROM attendance_violations
       WHERE employee_id = ?
         AND violation_type = ?
         AND violation_date >= ?
         AND status <> 'dismissed'
       ORDER BY violation_date DESC`,
      [employeeId, violationType, since.toISOString().slice(0, 10)]
    );

    if (!violations.length) continue;

    const openCase = await findOpenCaseForEmployee({ employeeId, caseType: 'attendance' });

    const violationIds = violations.map((row) => row.id);
    if (openCase?.id) {
      await attachViolationsToCase({ caseId: openCase.id, violationIds, updatedBy: createdBy });
      await db.query(
        `UPDATE attendance_violations SET status = 'escalated'
         WHERE id IN (${violationIds.map(() => '?').join(',')})`,
        violationIds
      );
      triggeredCases.push(openCase.id);
      continue;
    }

    const created = await createCaseFromViolations({
      employeeId,
      violationIds,
      severity: rule?.severity || null,
      createdBy,
    });

    triggeredCases.push(created.caseId);

    await db.query(
      `UPDATE attendance_violations SET status = 'escalated'
       WHERE id IN (${violationIds.map(() => '?').join(',')})`,
      violationIds
    );

    const caseRow = await db.getOne(
      `SELECT dc.case_number, e.first_name, e.last_name
       FROM disciplinary_cases dc
       JOIN employees e ON dc.employee_id = e.employee_id
       WHERE dc.id = ?`,
      [created.caseId]
    );

    const violationDates = violations.map((row) => row.violation_date);

    if (String(rule?.action || '').toUpperCase() === 'NTE') {
      const template = policy?.notice_templates?.NTE || {};
      const subject = renderTemplate(template.subject, {
        case_number: caseRow?.case_number || `CASE-${created.caseId}`,
      });

      const content = renderTemplate(template.content, {
        case_number: caseRow?.case_number || `CASE-${created.caseId}`,
        employee_name: `${caseRow?.first_name || ''} ${caseRow?.last_name || ''}`.trim(),
        violation_dates: formatViolationDates(violationDates),
        policy_rule: buildPolicyRuleLabel(violationType, rule),
        due_date: 'TBD',
      });

      await createCaseNotice({
        caseId: created.caseId,
        noticeType: 'NTE',
        subject,
        content,
        recipientEmployeeId: employeeId,
        sentVia: 'internal',
        createdBy,
        autoGenerated: true,
        sendNow: false,
      });

      await notifyHrPortalUsers({
        title: `NTE draft created (${caseRow?.case_number || created.caseId})`,
        message: `Notice to Explain draft is ready for review for employee ${employeeId}.`,
        category: 'due_process',
        referenceModule: 'due_process',
        referenceId: `case:${created.caseId}`,
      });
    }
  }

  return triggeredCases;
};

export const listAttendanceViolations = async ({
  employeeId,
  status,
  violationType,
  startDate,
  endDate,
  limit = 20,
  page = 1,
}) => {
  const normalizedLimit = Math.min(Math.max(Number(limit) || 20, 1), 100);
  const normalizedPage = Math.max(Number(page) || 1, 1);
  const offset = (normalizedPage - 1) * normalizedLimit;

  const params = [];
  const where = [];

  if (employeeId) {
    where.push('av.employee_id = ?');
    params.push(Number(employeeId));
  }

  if (status) {
    where.push('av.status = ?');
    params.push(status);
  }

  if (violationType) {
    where.push('av.violation_type = ?');
    params.push(violationType);
  }

  if (startDate) {
    where.push('av.violation_date >= ?');
    params.push(startDate);
  }

  if (endDate) {
    where.push('av.violation_date <= ?');
    params.push(endDate);
  }

  const whereSql = where.length ? `WHERE ${where.join(' AND ')}` : '';

  const data = await db.getAll(
    `SELECT av.*, e.first_name, e.last_name, e.employee_code
     FROM attendance_violations av
     LEFT JOIN employees e ON av.employee_id = e.employee_id
     ${whereSql}
     ORDER BY av.violation_date DESC
     LIMIT ${normalizedLimit} OFFSET ${offset}`,
    params
  );

  const countRow = await db.getOne(
    `SELECT COUNT(*) AS total FROM attendance_violations av ${whereSql}`,
    params
  );

  return {
    data,
    count: Number(countRow?.total || 0),
  };
};

export const updateViolationStatus = async ({ violationId, status, remarks = null, updatedBy = null }) => {
  const existing = await db.getOne('SELECT * FROM attendance_violations WHERE id = ?', [violationId]);
  if (!existing) return null;

  await db.update('attendance_violations', {
    status,
    remarks,
  }, 'id = ?', [violationId]);

  await logDueProcessAudit({
    userId: updatedBy,
    entityType: 'attendance_violation',
    entityId: violationId,
    action: 'update_status',
    oldValues: { status: existing.status, remarks: existing.remarks },
    newValues: { status, remarks },
  });

  return true;
};

export const scanMissingLogViolations = async ({ startDate, endDate, createdBy = null }) => {
  const rows = await db.getAll(
    `SELECT attendance_id, employee_id, date, time_in, time_out, status
     FROM attendance
     WHERE date BETWEEN ? AND ?`,
    [startDate, endDate]
  );

  const created = [];
  const affectedEmployees = new Set();
  for (const row of rows) {
    if (row.status !== 'absent' && (!row.time_in || !row.time_out)) {
      const violationId = await createViolationRecord({
        employeeId: row.employee_id,
        attendanceId: row.attendance_id,
        violationType: 'missing_log',
        violationMinutes: null,
        violationDate: row.date,
        policyRuleTriggered: 'missing_log',
        autoGenerated: true,
        createdBy,
      });
      if (violationId) created.push(violationId);
      affectedEmployees.add(row.employee_id);
    }
  }

  for (const employeeId of affectedEmployees) {
    await evaluateViolationThresholds({ employeeId, createdBy });
  }

  return created;
};
