import logger from '../utils/logger.js';
import {
  listAttendanceViolations,
  createViolationRecord,
  updateViolationStatus,
  evaluateViolationThresholds,
  scanMissingLogViolations,
} from '../services/attendanceViolationService.js';

export const getAttendanceViolations = async (req, res, next) => {
  try {
    const { employee_id, status, violation_type, start_date, end_date, limit, page } = req.query;

    const result = await listAttendanceViolations({
      employeeId: employee_id,
      status,
      violationType: violation_type,
      startDate: start_date,
      endDate: end_date,
      limit,
      page,
    });

    return res.json({
      success: true,
      data: result.data,
      count: result.count,
    });
  } catch (error) {
    logger.error('Get attendance violations error:', error);
    next(error);
  }
};

export const createAttendanceViolation = async (req, res, next) => {
  try {
    const {
      employee_id,
      attendance_id,
      violation_type,
      violation_minutes,
      violation_date,
      remarks,
    } = req.body;

    if (!employee_id || !violation_type || !violation_date) {
      return res.status(400).json({
        success: false,
        message: 'employee_id, violation_type, and violation_date are required.',
      });
    }

    const createdBy = req.user?.user_id || null;

    const violationId = await createViolationRecord({
      employeeId: employee_id,
      attendanceId: attendance_id || null,
      violationType: violation_type,
      violationMinutes: violation_minutes ?? null,
      violationDate: violation_date,
      policyRuleTriggered: null,
      autoGenerated: false,
      remarks,
      createdBy,
    });

    await evaluateViolationThresholds({ employeeId: employee_id, createdBy });

    return res.status(201).json({
      success: true,
      message: 'Attendance violation created successfully',
      data: { id: violationId },
    });
  } catch (error) {
    logger.error('Create attendance violation error:', error);
    next(error);
  }
};

export const updateAttendanceViolationStatus = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { status, remarks } = req.body;

    if (!status) {
      return res.status(400).json({
        success: false,
        message: 'status is required',
      });
    }

    const updated = await updateViolationStatus({
      violationId: id,
      status,
      remarks,
      updatedBy: req.user?.user_id || null,
    });

    if (!updated) {
      return res.status(404).json({
        success: false,
        message: 'Attendance violation not found',
      });
    }

    return res.json({
      success: true,
      message: 'Attendance violation updated',
    });
  } catch (error) {
    logger.error('Update attendance violation status error:', error);
    next(error);
  }
};

export const scanAttendanceViolations = async (req, res, next) => {
  try {
    const { start_date, end_date } = req.body;

    if (!start_date || !end_date) {
      return res.status(400).json({
        success: false,
        message: 'start_date and end_date are required',
      });
    }

    const created = await scanMissingLogViolations({
      startDate: start_date,
      endDate: end_date,
      createdBy: req.user?.user_id || null,
    });

    return res.json({
      success: true,
      message: 'Attendance violation scan completed',
      data: { created_count: created.length },
    });
  } catch (error) {
    logger.error('Scan attendance violations error:', error);
    next(error);
  }
};
