import logger from '../utils/logger.js';
import {
  listDisciplinaryCases,
  getDisciplinaryCaseById,
  createDisciplinaryCase,
  updateCase,
  createCaseNotice,
  sendCaseNotice,
  acknowledgeNotice,
  submitExplanation,
  scheduleHearing,
  addDecision,
} from '../services/disciplinaryCaseService.js';
import * as db from '../config/db.js';

export const getDisciplinaryCases = async (req, res, next) => {
  try {
    const { status, employee_id, limit, page } = req.query;

    const result = await listDisciplinaryCases({
      status,
      employeeId: employee_id,
      limit,
      page,
    });

    return res.json({
      success: true,
      data: result.data,
      count: result.count,
    });
  } catch (error) {
    logger.error('Get disciplinary cases error:', error);
    next(error);
  }
};

export const getDisciplinaryCaseDetail = async (req, res, next) => {
  try {
    const { id } = req.params;
    const caseDetail = await getDisciplinaryCaseById(id);

    if (!caseDetail) {
      return res.status(404).json({
        success: false,
        message: 'Case not found',
      });
    }

    return res.json({
      success: true,
      data: caseDetail,
    });
  } catch (error) {
    logger.error('Get disciplinary case detail error:', error);
    next(error);
  }
};

export const createDisciplinaryCaseManual = async (req, res, next) => {
  try {
    const { employee_id, case_type, severity, assigned_hr_id, assigned_manager_id } = req.body;

    if (!employee_id) {
      return res.status(400).json({
        success: false,
        message: 'employee_id is required',
      });
    }

    const createdBy = req.user?.user_id || null;
    const result = await createDisciplinaryCase({
      employeeId: employee_id,
      caseType: case_type || 'attendance',
      severity: severity || null,
      assignedHrId: assigned_hr_id || null,
      assignedManagerId: assigned_manager_id || null,
      createdBy,
    });

    return res.status(201).json({
      success: true,
      message: 'Case created successfully',
      data: result,
    });
  } catch (error) {
    logger.error('Create disciplinary case error:', error);
    next(error);
  }
};

export const updateDisciplinaryCase = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { status, severity, assigned_hr_id, assigned_manager_id } = req.body;

    const updates = {};
    if (status) updates.status = status;
    if (severity !== undefined) updates.severity = severity;
    if (assigned_hr_id !== undefined) updates.assigned_hr_id = assigned_hr_id || null;
    if (assigned_manager_id !== undefined) updates.assigned_manager_id = assigned_manager_id || null;

    if (Object.keys(updates).length === 0) {
      return res.status(400).json({
        success: false,
        message: 'No updates provided',
      });
    }

    const updated = await updateCase({
      caseId: id,
      updates,
      updatedBy: req.user?.user_id || null,
      ipAddress: req.ip,
    });

    if (!updated) {
      return res.status(404).json({
        success: false,
        message: 'Case not found',
      });
    }

    return res.json({
      success: true,
      message: 'Case updated',
    });
  } catch (error) {
    logger.error('Update disciplinary case error:', error);
    next(error);
  }
};

export const createCaseNoticeHandler = async (req, res, next) => {
  try {
    const { id } = req.params;
    const {
      notice_type,
      subject,
      content,
      sent_via,
      due_date,
      send_now,
    } = req.body;

    if (!notice_type || !subject || !content) {
      return res.status(400).json({
        success: false,
        message: 'notice_type, subject, and content are required',
      });
    }

    const caseRow = await db.getOne('SELECT employee_id FROM disciplinary_cases WHERE id = ?', [id]);
    if (!caseRow) {
      return res.status(404).json({
        success: false,
        message: 'Case not found',
      });
    }

    const noticeId = await createCaseNotice({
      caseId: id,
      noticeType: notice_type,
      subject,
      content,
      recipientEmployeeId: caseRow.employee_id,
      sentVia: sent_via || 'internal',
      dueDate: due_date || null,
      createdBy: req.user?.user_id || null,
      autoGenerated: false,
      sendNow: Boolean(send_now),
    });

    return res.status(201).json({
      success: true,
      message: 'Notice created',
      data: { id: noticeId },
    });
  } catch (error) {
    logger.error('Create case notice error:', error);
    next(error);
  }
};

export const sendCaseNoticeHandler = async (req, res, next) => {
  try {
    const { notice_id } = req.params;

    await sendCaseNotice({
      noticeId: notice_id,
      caseId: null,
      sentVia: null,
      sentBy: req.user?.user_id || null,
    });

    return res.json({
      success: true,
      message: 'Notice sent successfully',
    });
  } catch (error) {
    logger.error('Send case notice error:', error);
    next(error);
  }
};

export const acknowledgeCaseNotice = async (req, res, next) => {
  try {
    const { notice_id } = req.params;
    const employeeId = req.user?.employee_id;

    if (!employeeId) {
      return res.status(403).json({
        success: false,
        message: 'Employee context required',
      });
    }

    await acknowledgeNotice({ noticeId: notice_id, employeeId });

    return res.json({
      success: true,
      message: 'Notice acknowledged',
    });
  } catch (error) {
    logger.error('Acknowledge case notice error:', error);
    next(error);
  }
};

export const submitCaseExplanation = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { explanation_text, attachment_url } = req.body;
    const employeeId = req.user?.employee_id;

    if (!employeeId) {
      return res.status(403).json({
        success: false,
        message: 'Employee context required',
      });
    }

    if (!explanation_text) {
      return res.status(400).json({
        success: false,
        message: 'explanation_text is required',
      });
    }

    const caseRow = await db.getOne(
      'SELECT employee_id FROM disciplinary_cases WHERE id = ?',
      [id]
    );

    if (!caseRow || Number(caseRow.employee_id) !== Number(employeeId)) {
      return res.status(403).json({
        success: false,
        message: 'You are not authorized to submit an explanation for this case',
      });
    }

    const explanationId = await submitExplanation({
      caseId: id,
      employeeId,
      explanationText: explanation_text,
      attachmentUrl: attachment_url || null,
    });

    return res.status(201).json({
      success: true,
      message: 'Explanation submitted',
      data: { id: explanationId },
    });
  } catch (error) {
    logger.error('Submit case explanation error:', error);
    next(error);
  }
};

export const scheduleCaseHearing = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { hearing_datetime, hearing_type, location_or_link, investigator_id, notes, send_notice } = req.body;

    if (!hearing_datetime || !hearing_type) {
      return res.status(400).json({
        success: false,
        message: 'hearing_datetime and hearing_type are required',
      });
    }

    const hearingId = await scheduleHearing({
      caseId: id,
      hearingDatetime: hearing_datetime,
      hearingType: hearing_type,
      locationOrLink: location_or_link || null,
      investigatorId: investigator_id || null,
      notes: notes || null,
      createdBy: req.user?.user_id || null,
      sendNotice: Boolean(send_notice),
    });

    return res.status(201).json({
      success: true,
      message: 'Hearing scheduled',
      data: { id: hearingId },
    });
  } catch (error) {
    logger.error('Schedule case hearing error:', error);
    next(error);
  }
};

export const issueCaseDecision = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { decision_type, penalty_days, effective_date, decision_summary, send_notice } = req.body;

    if (!decision_type) {
      return res.status(400).json({
        success: false,
        message: 'decision_type is required',
      });
    }

    const decisionId = await addDecision({
      caseId: id,
      decisionType: decision_type,
      penaltyDays: penalty_days || null,
      effectiveDate: effective_date || null,
      decisionSummary: decision_summary || null,
      approvedBy: req.user?.user_id || null,
      sendNotice: Boolean(send_notice),
    });

    return res.status(201).json({
      success: true,
      message: 'Decision recorded',
      data: { id: decisionId },
    });
  } catch (error) {
    if (error.code === 'DUE_PROCESS_NTE_REQUIRED' || error.code === 'DUE_PROCESS_RESPONSE_REQUIRED') {
      return res.status(400).json({
        success: false,
        message: error.message,
      });
    }
    logger.error('Issue case decision error:', error);
    next(error);
  }
};

export const getMyDueProcessNotices = async (req, res, next) => {
  try {
    const employeeId = req.user?.employee_id;
    if (!employeeId) {
      return res.status(403).json({
        success: false,
        message: 'Employee context required',
      });
    }

    const notices = await db.getAll(
      `SELECT cn.*, dc.case_number
       FROM case_notices cn
       JOIN disciplinary_cases dc ON cn.case_id = dc.id
       WHERE cn.recipient_employee_id = ?
       ORDER BY cn.created_at DESC`,
      [employeeId]
    );

    return res.json({
      success: true,
      data: notices,
      count: notices.length,
    });
  } catch (error) {
    logger.error('Get my due process notices error:', error);
    next(error);
  }
};

export const getMyDueProcessCases = async (req, res, next) => {
  try {
    const employeeId = req.user?.employee_id;
    if (!employeeId) {
      return res.status(403).json({
        success: false,
        message: 'Employee context required',
      });
    }

    const cases = await db.getAll(
      `SELECT dc.*
       FROM disciplinary_cases dc
       WHERE dc.employee_id = ?
       ORDER BY dc.created_at DESC`,
      [employeeId]
    );

    return res.json({
      success: true,
      data: cases,
      count: cases.length,
    });
  } catch (error) {
    logger.error('Get my due process cases error:', error);
    next(error);
  }
};
